#!/bin/sh

############################################################################################################
# Set variables
############################################################################################################

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"
app_port=`config-get app_port`
 
############################################################################################################
# Reconfigure
############################################################################################################

juju-log "Reconfiguring app by installing hook again."

config_file_path=${app_dir}/${app_name}.conf
if [ -f $config_file_path ]; then
  sed -i "s/@@APP_NAME@@/${app_name}/" $config_file_path
  sed -i "s/@@APP_PORT@@/${app_port}/" $config_file_path
fi

############################################################################################################
# Restart
############################################################################################################

service ${app_name} status
rc=$?

if [ $rc != 0 ]; then
  juju-log "(re)starting app"
  service ${app_name} restart
fi
