#!/bin/bash
set -eu # -x for verbose
umask 002

############################################################################################################
# Set variables
############################################################################################################
install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"
app_user=`config-get app_user`
app_artifact=`config-get app_artifact`
repository_url=`config-get repository_url`
app_port=`config-get app_port`
app_instances=`config-get app_instances`
vertx_version=`config-get vertx_version`

############################################################################################################
# Install Vert.x
############################################################################################################

juju-log "Installing Vert.x ${vertx_version}..."
apt-get -y install -qq openjdk-7-jdk
wget http://vertx.io/downloads/vert.x-${vertx_version}.tar.gz -o /tmp/wget.log
tar -C /opt -zxf vert.x-${vertx_version}.tar.gz
ln -s /opt/vert.x-${vertx_version}/bin/vertx /usr/local/bin/vertx
# reconfigure logging to use the OS standard location
mv /opt/vert.x-${vertx_version}/conf/logging.properties /opt/vert.x-${vertx_version}/conf/logging.properties.original
cat > /opt/vert.x-${vertx_version}/conf/logging.properties <<EOS
handlers=java.util.logging.FileHandler
java.util.logging.FileHandler.level=INFO
java.util.logging.FileHandler.formatter=org.vertx.java.core.logging.impl.VertxLoggerFormatter
java.util.logging.FileHandler.pattern=/var/log/${app_name}.log

.level=INFO
org.vertx.level=INFO
com.hazelcast.level=SEVERE
EOS

############################################################################################################
# Install The App
############################################################################################################

juju-log "Installing ${app_name}..."
mkdir -p ${app_dir}/mods
cd ${app_dir}
/usr/local/bin/vertx install ${app_name} -repo ${repository_url}

############################################################################################################
# Create upstart config
############################################################################################################

cat > /etc/init/${app_name}.conf <<EOS
description "${app_name} Vert.x server"
 
start on (net-device-up
          and local-filesystems
          and runlevel [2345])
stop on runlevel [!2345]
 
expect fork
respawn
 
script
  cd ${app_dir}
  exec /usr/local/bin/vertx runmod ${app_name} -conf ${app_name}.conf -instances ${app_instances} >> /var/log/vertx.log 2>&1 &
end script
EOS

############################################################################################################
# Configure the App
############################################################################################################

juju-log "Configuring ${app_name}..."

config_file_path=${app_dir}/${app_name}.conf
if [ -f $config_file_path ]; then
  sed -i 's/"app_name"[ ]*:[ ]*".*"/"app_name": "${app_name}"/' $config_file_path
  sed -i 's/"app_port"[ ]*:[ ]*[0-9][0-9]*/"app_port": ${app_port}/' $config_file_path
fi

############################################################################################################
# Open the listener port when the service is exposed
############################################################################################################

# Disabled since we expose the app with a proxy
# open-port ${app_port}/TCP

