#!/bin/sh

app_name=`config-get app_name`
juju-log "mongodb server is gone!"

############################################################################################################
# Set variables
############################################################################################################

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"

############################################################################################################
# Configure App to know about mongodb
############################################################################################################

juju-log "configuring ${app_name} to work with the mongodb service"

config_file_path=${app_dir}/${app_name}.conf
if [ -f $config_file_path ]; then
  sed -i 's/"mongodb_host"[ ]*:[ ]*".*"/"mongodb_host": ""/' $config_file_path
  sed -i 's/"mongodb_port"[ ]*:[ ]*[0-9][0-9]*/"mongodb_port": 0/' $config_file_path
fi

############################################################################################################
# Restart
############################################################################################################

service ${app_name} status
rc=$?

if [ $rc != 0 ]; then
  juju-log "(re)starting app"
  service ${app_name} restart
fi
