#!/bin/sh

app_name=`config-get app_name`
juju-log "redis server is gone!"
# TODO: remove config?

############################################################################################################
# Restart
############################################################################################################

service ${app_name} status
rc=$?

if [ $rc != 0 ]; then
  juju-log "(re)starting app"
  service ${app_name} restart
fi
