options:
  vertx_version:
    type: string
    default: 1.3.1.final
    description: Vert.x Version
  app_name:
    type: string
    default: myapp
    description: Main Vert.x module name
  app_port:
    type: int
    default: 8080
    description: Port where the application will handle requests
  app_instances:
    type: int
    default: 1
    description: Number of instances per server
  repository_url:
    type: string
    default: "http://github.com/vert-x/vertx-mods"
    description: Application binary artifact URL without the artifact name
  install_root:
    type: string
    default: /opt
    description: Install the application in app_name under this directory
