#!/bin/bash

set -eu 

# Get the database settings; if not set, wait for this hook to be
# invoked again
host=`relation-get private-address`
if [ -z "$host" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

relation_port=`relation-get port`
port=${relation_port:-6379}

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"

configure_app() {
  juju-log "configuring ${app_name} to work with the redis service"

config_file_path=${app_dir}/${app_name}.conf
  if [ -f $config_file_path ]; then
    sed -i "s/@@REDIS_HOST@@/${host}/" $config_file_path
    sed -i "s/@@REDIS_PORT@@/${port}/" $config_file_path
  fi

  app_port=`config-get app_port`
  open-port $app_port/TCP
}
configure_app

juju-log "(re)starting app"
service ${app_name} restart || service ${app_name} start

